### ISSUE TITLE
MongoDB + Pagination 기능을 통한 메타데이터 Read 최적화

### ISSUE THREAD

**Issue by leeseungmin4966** [BEOKS/DicomProject#272]
## 문제점

현재 메인 페이지에서 메타데이터들을 읽어들이는 방식은 findAll api를 통해 해당 프로젝트 내에 존재하는 모든 metadata 정보를 읽어들여 리스트 형식으로 클라이언트에 제공한다.

이러한 방식의 문제점은 프로젝트 내에서 메타데이터의 개수가 증가함에따라 한번에 읽어들이는 데이터의 크기가 점점 증가하여 최종적으로는 Read 연산의 효율을 떨어뜨린다.

## 해결방안

해당 문제를 해결하기 위해 서버 단에서 pagination 기능을 제공해주고 페이지 내의 메타데이터 값만 리스트로 전달 해 주는 방식이 더 효율적이라 생각한다.

## 시각자료

<img width="820" alt="스크린샷 2022-05-14 오후 5 25 12" src="https://user-images.githubusercontent.com/40168455/168417682-61f9d297-a75a-48e0-a567-763ec59e157e.png">

위와 같은 쿼리로 페이지 번호와 페이지 크기를 정해주면,

<img width="406" alt="스크린샷 2022-05-14 오후 5 21 56 2" src="https://user-images.githubusercontent.com/40168455/168417706-1d5aa07c-fe2e-4c1a-8913-53f7c52aece4.png">

이와 같이 content 내에서 메타데이터 리스트 정보와 페이지 관련 정보를 반환해준다. 이 페이지 정보를 이용하여 클라이언트에서, 페이지 UI를 관리하면 될듯 하다.

* url에서 page&size 정보를 넣어주지 않으면 기본 값으로 page = 0 & size = 20 으로 세팅된다.
* 필터기능도 현재 개발중이며, page와 size 정보와 같이 url parameter로 전달받아 처리할 예정이다.

## 참고자료

https://www.baeldung.com/queries-in-spring-data-mongodb

https://betterjavacode.com/spring-boot/spring-boot-crud-application-example-with-mongodb

https://stackoverflow.com/questions/29030542/pagination-with-mongotemplate

https://stackoverflow.com/questions/41746370/spring-data-mongo-case-insensitive-like-query

**Comment by leeseungmin4966** [comment]
@doheez 

궁금한거 있으면 말해줘

**Comment by doheez** [comment]
## 프론트엔드 문제점
현재 메타 데이터 테이블은 MUI 프레임워크에서 제공하는 client-side pagination을 사용한다. 전체 메타 데이터를 한 번에 로드한 후, 프론트엔드 단에서 전체 데이터 개수를 가지고 paging하는 방식이다.

따라서 프론트에서 기존 pagination 방식을 변경하지 않고 페이지별로 데이터를 불러온다면, 한 페이지 안에 포함되는 데이터가 (실제로는 전체 메타 데이터의 일부일 뿐인데도) 메타 데이터의 전부인 것으로 인식되어 다음 페이지로 이동하는 버튼 자체가 보이지 않게 된다.

## 해결 방법
### Option 1
UI 프레임워크를 사용하지 않고 직접 테이블을 구현한다. 테이블 행 선택, 정렬, 필터링, Collapsible 행 등 다양한 기능을 포함해야 하므로 일일이 코드를 작성하는 것은 매우 어렵고 시간상 불가능할 것 같다.

### Option 2
메타 데이터의 lazy loading을 구현하기 위해 Devextreme에서 제공하는 Data Grid의 `Remote Virtual Scrolling` 기능을 사용한다. 이를 통해 메타 데이터 테이블을 server-side pagination 방식으로 변경할 수 있을 것이라 생각한다. 이를 위해 우선 Devextrme Data Grid로 테이블 리팩토링이 선행되어야 한다. 추후 pagination 방식을 변경하기 위해 참고 문서를 기록해둔다.

## Reference
[1] https://supportcenter.devexpress.com/ticket/details/t1001940/datagrid-how-to-add-server-side-paging
[2] https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/remoteOperations/#paging
[3] https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RemoteVirtualScrolling/React/Light/
